{{- range $name, $config := .Values.services }}
apiVersion: v1
kind: Service
metadata:
  name: {{ $.Release.Name | default "default-release" }}-{{ $name }}
  labels:
    app: {{ $.Chart.Name }}
spec:
  type: {{ $config.type | default $.Values.defaultServiceType }}
  ports:
  - port: {{ $config.port }}
    targetPort: {{ $config.targetPort | default $config.port }}
  selector:
    app: {{ $.Chart.Name }}
---
{{ end }}
